using System.Text.Json.Serialization;

namespace PayStack.Net.Models.Requests;

/// <summary>Request body for <c>POST /transaction/initialize</c>.</summary>
public sealed class InitializeTransactionRequest
{
    /// <summary>Amount to charge, in the currency's subunit (e.g. kobo for NGN). Required.</summary>
    [JsonPropertyName("amount")]
    public required string Amount { get; set; }

    /// <summary>Customer's email address. Required — Paystack uses this to identify/create the customer.</summary>
    [JsonPropertyName("email")]
    public required string Email { get; set; }

    /// <summary>Restricts which payment channels are offered. Use <see cref="Common.PayStackChannel"/> constants. Defaults to all enabled channels on your integration.</summary>
    public List<string>? Channels { get; set; }

    /// <summary>ISO 4217 currency code. Defaults to your integration's default currency.</summary>
    public string? Currency { get; set; }

    /// <summary>Unique transaction reference. Auto-generated by Paystack when omitted.</summary>
    public string? Reference { get; set; }

    /// <summary>URL to redirect the customer to after payment.</summary>
    public string? CallbackUrl { get; set; }

    /// <summary>Plan code to subscribe the customer to. When set, this overrides <see cref="Amount"/> with the plan's amount.</summary>
    public string? Plan { get; set; }

    /// <summary>Number of times to charge for a plan before stopping, when combined with <see cref="Plan"/>.</summary>
    public int? InvoiceLimit { get; set; }

    /// <summary>Arbitrary JSON-serializable data to attach to the transaction.</summary>
    public object? Metadata { get; set; }

    /// <summary>Split code of a pre-created transaction split to apply.</summary>
    public string? SplitCode { get; set; }

    /// <summary>Subaccount code the payment should be split with.</summary>
    public string? Subaccount { get; set; }

    /// <summary>Flat fee (in subunits) to charge in addition to the normal Paystack fee when using <see cref="Subaccount"/>.</summary>
    public int? TransactionCharge { get; set; }

    /// <summary>Who bears the Paystack fee for a split payment: "account" (default) or "subaccount".</summary>
    public string? Bearer { get; set; }
}
